# Generated by Django 5.0.7 on 2024-08-13 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=150, verbose_name='Прізвище')),
                ('image', models.ImageField(upload_to='profile_images/', verbose_name='Зображення профілю')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Обкладинка профілю')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Місто')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Країна')),
                ('status', models.TextField(blank=True, max_length=300, null=True, verbose_name='Статус')),
                ('type', models.CharField(choices=[('private', 'Приватний'), ('public', 'Публічний')], default='public', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
