# Generated by Django 5.0.7 on 2024-08-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('man', 'Чоловік'), ('woman', 'Жінка'), ('other', 'Інше')], default='other', max_length=100, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефону'),
        ),
    ]
