# Generated by Django 5.0.7 on 2024-10-08 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at'], 'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Учасник групи', 'verbose_name_plural': 'Учасники груп'},
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('user', 'group')},
        ),
    ]
